import { VideoItem } from "@/lib/types";

/**
 * Video thật từ kênh YouTube MakerViet (https://youtube.com/@makerviet).
 * Toàn bộ ID đã kiểm tra công khai + nhúng được (oEmbed 200) ngày 2026-09-06.
 *
 * Giai đoạn "Khám Phá" và "Lập Trình" hiện chưa có video — cố ý để trống thay vì
 * điền video giả. Bổ sung bằng cách thêm dòng vào Google Sheet "Videos"
 * (xem lib/sheets.ts) hoặc thêm trực tiếp vào mảng dưới đây.
 */

const YT = (id: string) => ({
  youtubeUrl: `https://www.youtube.com/watch?v=${id}`,
  youtubeId: id,
  // hqdefault luôn tồn tại, kể cả video cũ không có bản maxres
  thumbnail: `https://i.ytimg.com/vi/${id}/hqdefault.jpg`,
});

export const VIDEOS: VideoItem[] = [
  {
    id: "mv-thingbot-kit-2026",
    title: "Hướng dẫn lắp bộ Kit ThingBot | Phiên bản 2025–2026",
    ...YT("N72W9EYd26I"),
    stage: "iot-robot",
    ageRange: "10-15",
    tags: ["thingbot", "lắp ráp", "robot"],
    description:
      "Hướng dẫn lắp ráp đầy đủ bộ Kit ThingBot phiên bản 2025–2026 — từ khung xe đến mạch điều khiển.",
    featured: true,
    published: true,
    order: 1,
    createdAt: "2025-12-25",
  },
  {
    id: "mv-thingbot-gioi-thieu",
    title: "Giới thiệu bộ Kit ThingBot",
    ...YT("Y9jM5MlzRVY"),
    stage: "iot-robot",
    ageRange: "10-15",
    tags: ["thingbot", "giới thiệu", "robot"],
    description:
      "Bộ Kit ThingBot gồm những gì và học sinh làm được gì với nó.",
    featured: true,
    published: true,
    order: 2,
    createdAt: "2025-03-07",
  },
  {
    id: "mv-thingbot-phan-cung",
    title: "Giới thiệu phần cứng ThingBot",
    ...YT("9mNA89_0LQg"),
    stage: "iot-robot",
    ageRange: "10-15",
    tags: ["thingbot", "phần cứng", "mạch điện"],
    description:
      "Các khối phần cứng của ThingBot: mạch điều khiển, động cơ, cảm biến và cách chúng nối với nhau.",
    featured: false,
    published: true,
    order: 3,
    createdAt: "2025-03-07",
  },
  {
    id: "mv-cobot-lap-rap",
    title: "Hướng dẫn lắp ráp CoBot",
    ...YT("J4CTvk9BN0E"),
    stage: "iot-robot",
    ageRange: "10-15",
    tags: ["cobot", "lắp ráp", "cơ khí"],
    description: "Từng bước lắp ráp robot CoBot cho lớp học STEM.",
    featured: false,
    published: true,
    order: 4,
    createdAt: "2023-12-24",
  },
  {
    id: "mv-arduino-bai-1",
    title: "Bài 1: Hello Arduino | Lập trình Arduino",
    ...YT("4SfpeZu1VDc"),
    stage: "iot-robot",
    ageRange: "12-18",
    tags: ["arduino", "lập trình nhúng", "bài giảng"],
    description:
      "Giới thiệu Arduino, cài đặt Arduino IDE, nạp chương trình đầu tiên và dùng mô phỏng khi chưa có mạch thật.",
    featured: true,
    published: true,
    order: 5,
    createdAt: "2023-05-26",
  },
  {
    id: "mv-arduino-bai-2",
    title: "Bài 2: Lập trình điều khiển động cơ với Arduino",
    ...YT("JTAzVEyW3TU"),
    stage: "iot-robot",
    ageRange: "12-18",
    tags: ["arduino", "động cơ", "servo"],
    description:
      "Động cơ DC và động cơ servo: nguyên lý hoạt động và cách lập trình điều khiển bằng Arduino.",
    featured: false,
    published: true,
    order: 6,
    createdAt: "2023-05-26",
  },
  {
    id: "mv-thingedublock",
    title: "Giới thiệu phần mềm ThingEduBlock",
    ...YT("Tfql_FykiT4"),
    stage: "tu-duy",
    ageRange: "8-12",
    tags: ["thingedublock", "lập trình khối", "trực quan"],
    description:
      "Lập trình bằng khối lệnh kéo–thả với ThingEduBlock — bước đệm trước khi viết code chữ.",
    featured: true,
    published: true,
    order: 7,
    createdAt: "2025-03-07",
  },
  {
    id: "mv-maker-tutor-b3",
    title: "Maker Tech-Tutor — Buổi 3: Linh kiện điện tử cơ bản",
    ...YT("SUikzdQNBFs"),
    stage: "chia-se",
    ageRange: "15-18",
    tags: ["mentor", "đào tạo", "điện tử"],
    description:
      "Buổi 3 chương trình đào tạo Gia sư công nghệ Maker (Maker Tech-Tutor) — linh kiện điện tử cơ bản.",
    featured: true,
    published: true,
    order: 8,
    createdAt: "2023-11-26",
  },
  {
    id: "mv-vrc-2022-chung-ket",
    title: "Vietnam Robotics Challenge 2022 — Vòng chung kết (video 360)",
    ...YT("iewncoJbA-8"),
    stage: "chia-se",
    ageRange: "15-18",
    tags: ["vrc", "cuộc thi", "360"],
    description:
      "Vòng chung kết Vietnam Robotics Challenge 2022 quay bằng camera 360 độ.",
    featured: false,
    published: true,
    order: 9,
    createdAt: "2022-06-28",
  },
  {
    id: "mv-vsc-vrc-2020-2022",
    title: "Vietnam Robotics Challenge — Hình ảnh cuộc thi 2020–2022",
    ...YT("-bEW37WDVYo"),
    stage: "chia-se",
    ageRange: "15-18",
    tags: ["vrc", "vsc", "cuộc thi"],
    description:
      "Chuỗi cuộc thi VSC 2020 và VRC 2022 dành cho học sinh phổ thông toàn quốc, do MakerViet đồng hành.",
    featured: false,
    published: true,
    order: 10,
    createdAt: "2022-06-19",
  },
  {
    id: "mv-fgc-2022-welcome",
    title: "FIRST Global Challenge 2022 — Đội tuyển Việt Nam tới Geneva (video 360)",
    ...YT("YCM-Dfv8YQ0"),
    stage: "chia-se",
    ageRange: "15-18",
    tags: ["first global", "đội tuyển", "360"],
    description:
      "Đội tuyển Việt Nam có mặt tại Palexpo Geneva trong FIRST Global Challenge 2022.",
    featured: false,
    published: true,
    order: 11,
    createdAt: "2022-10-12",
  },
  {
    id: "mv-fgc-2022-before",
    title: "FIRST Global Challenge 2022 — Trước giờ thi đấu (video 360)",
    ...YT("i7oL93xJUXQ"),
    stage: "chia-se",
    ageRange: "15-18",
    tags: ["first global", "hậu trường", "360"],
    description: "Không khí chuẩn bị trước ngày thi FIRST Global Challenge 2022.",
    featured: false,
    published: true,
    order: 12,
    createdAt: "2022-10-12",
  },
  {
    id: "mv-fgc-2022-geneva",
    title: "FIRST Global Challenge 2022 — Hồ Geneva (video 360)",
    ...YT("Vev1FBY5HxI"),
    stage: "chia-se",
    ageRange: "15-18",
    tags: ["first global", "geneva", "360"],
    description: "Đội tuyển thăm hồ Geneva bên lề FIRST Global Challenge 2022.",
    featured: false,
    published: true,
    order: 13,
    createdAt: "2022-10-13",
  },
  {
    id: "mv-mobile-maker-explora",
    title: "Mobile Maker Tour 01 — ExploraScience Quy Nhơn (phần 2)",
    ...YT("8gXWkjrQyWI"),
    stage: "chia-se",
    ageRange: "10-18",
    tags: ["mobile maker", "quy nhơn", "khoa học"],
    description:
      "Ghé tổ hợp không gian khoa học ExploraScience Quy Nhơn cùng đoàn Mobile Maker.",
    featured: false,
    published: true,
    order: 14,
    createdAt: "2022-05-31",
  },
  {
    id: "mv-mobile-maker-fschool",
    title: "Mobile Maker Tour 01 — Bình minh tại Fschool Quy Nhơn",
    ...YT("Zuie0ciL9Rk"),
    stage: "chia-se",
    ageRange: "10-18",
    tags: ["mobile maker", "quy nhơn", "cộng đồng"],
    description: "Buổi sáng trong khuôn viên Fschool Quy Nhơn cùng đoàn Mobile Maker.",
    featured: false,
    published: true,
    order: 15,
    createdAt: "2022-05-28",
  },
];
